### ISSUE TITLE
Download of applications

### ISSUE THREAD

**Issue by pr130** [CorrelAid/projectutils#2]
As a project coordinator, I want to be able to quickly download applications for my project. 

First implementations for this are on the `applications` branch. 

Challenges:

- [ ] we collect all applications in one, single surveymonkey survey -> this poses challenges for permission management, i.e. a person with a API token would be able to access all applications, not only the applications for their project. Here, more research is needed to see what options are available through [surveymonkey's developer API](https://developer.surveymonkey.com/): can tokens be issued for single surveys? 
- [ ]  German implementation of data cleaning
- [x] messy data: the data that is available through the API is quite messy. column names are super long and not very informative because they include the complete question. here, some data cleaning would be necessary, e.g. with some `rename_with` logic. The implementation on `surveymonkey` is currently limited to the english version and only includes some simple janitor::clean_names
- [x] anonymized version: it should be possible to easily anonymize the data to distribute them to the team selection committee. There is a first implementation on `surveymonkey` that should be tested.
- [x] export motivation as markdown: export motivation questions as markdown document to make it easier to read. there is a first implementation on `surveymonkey`

**Comment by pr130** [comment]
added anonymized fake data in `tests/testthat/test_data/surveymonkey` so that you can work on this issue independently of having access to surveymonkey API.

**Comment by MKyhos** [comment]
After moving to Kobo, can this issue be closed? Otherwise, the label could be removed, if the requirements are still valid for the new survey tool. 🙏

**Comment by pr130** [comment]
thank you @MKyhos for pointing this out. indeed, the issue can be closed.
